Vega Expressions for Lasso Selection
vega/vega pull request #3388
Opened 2022-01-14 10:10 UTC by dvmoritzschoefl

![lassoexample](https://user-images.githubusercontent.com/77104411/149497952-226bc7a3-c5ec-429a-a853-19ad13e52c10.gif)

This PR includes the following vega expressions:

- **lassoPath** (generates a svg path from a lasso signal, can be directly used on a path mark)
- **lassoAppend** (handles the logic to append a point to the lasso signal)
- **intersectLasso** (performs the intersection tests for the lasso and returns the appropriate tuples)

There is an example specification added that allows to test the lasso (called lasso.vg.json). If this PR gets approved, I will create another PR for vega-lite that includes the generator for lasso selections.

2022-01-20 19:19 UTC, arvind requested changes
Hi @dvmoritzschoefl, this PR looks like a great start. I've left some line/block-level suggestions but three high-level thoughts:

1. I think it'd be useful to have these lasso functions remain as general purpose as possible rather than tightly coupled with Vega-Lite selections. So, I recommend removing any references to selections here. Instead, have this function return an array of scene graph items within the lasso and, in the expression string generated byVega-Lite, pass this array to the `vlSelectionTuples` function introduced in #3009 and improved in #3397 to extract `SELECTION_ID` and populate the selection stores.

2. Relatedly, I'm not sure I'm totally following why we have this function inverting pixels -> data coordinates. Can we not stay entirely in pixel space for the entirety of the hit testing process (i.e., an `intersectLasso` function instead)? I'm imagining the same steps you have currently (start with a lasso path, calculate the bounding box, `intersect` it with the scenegraph, and then validate which `pointInPolygon`), but you'd never make a roundtrip to data space at all. Instead, and following (1) above, we'd only go into data space once we have all the scene graph items that fall within the lasso and just to extract the `SELECTION_ID`. Does this make sense? I could very well believe I'm missing something though. 

3. A more minor point: in Vega and Vega-Lite, we default to a 2-space indent. Do you mind updating this file to follow that format? Thanks!

2022-01-24 11:46 UTC, dvmoritzschoefl commented
> Hi @dvmoritzschoefl, this PR looks like a great start. I've left some line/block-level suggestions but three high-level thoughts:
> 
> 1. I think it'd be useful to have these lasso functions remain as general purpose as possible rather than tightly coupled with Vega-Lite selections. So, I recommend removing any references to selections here. Instead, have this function return an array of scene graph items within the lasso and, in the expression string generated byVega-Lite, pass this array to the `vlSelectionTuples` function introduced in #3009 and improved in #3397 to extract `SELECTION_ID` and populate the selection stores.
> 2. Relatedly, I'm not sure I'm totally following why we have this function inverting pixels -> data coordinates. Can we not stay entirely in pixel space for the entirety of the hit testing process (i.e., an `intersectLasso` function instead)? I'm imagining the same steps you have currently (start with a lasso path, calculate the bounding box, `intersect` it with the scenegraph, and then validate which `pointInPolygon`), but you'd never make a roundtrip to data space at all. Instead, and following (1) above, we'd only go into data space once we have all the scene graph items that fall within the lasso and just to extract the `SELECTION_ID`. Does this make sense? I could very well believe I'm missing something though.
> 3. A more minor point: in Vega and Vega-Lite, we default to a 2-space indent. Do you mind updating this file to follow that format? Thanks!

1. I used the functions you mentioned, the function is now called 'intersectLasso' instead and does not use data space
2. solved
3. updated to 2-space indent

attached is a working lasso spec
[lasso.vg.zip](https://github.com/vega/vega/files/7925282/lasso.vg.zip)

2022-01-26 15:20 UTC, arvind commented on packages/vega-functions/src/functions/lasso.js
> +  const [testx, testy] = test;
```suggestion
function pointInPolygon(testx, testy, polygon) {
```
Seemed like an unnecessary array being constructed in `intersectLasso` to merely be destructured here?

2022-01-26 15:20 UTC, arvind commented on packages/vega-functions/src/functions/lasso.js
> +  var intersections = 0;
```suggestion
  let intersections = 0;
```

2022-01-26 15:20 UTC, arvind commented on packages/vega-functions/src/functions/lasso.js
> +  for (var i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
```suggestion
  let (var i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
```

2022-01-26 15:29 UTC, arvind commented on packages/vega-functions/src/functions/lasso.js
> +}
```suggestion
export function lassoPath(lasso) {
  return lasso.entries().reduce((svg, [i, [x, y]]) => {
    return svg += i === 0
      ? `M ${x},${y} `
      : i === lasso.length - 1
        ? ' Z'
        : `L ${x},${y} `
  }, '');
}
```

2022-01-26 15:38 UTC, arvind commented on packages/vega-functions/src/functions/lasso.js
> +  let (var i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
Sorry, heads up, I typo'd my suggestion.

2022-01-27 07:00 UTC, dvmoritzschoefl commented on packages/vega-functions/src/functions/lasso.js
> +  return (lasso ?? []).reduce((svg, [x, y], i) => {
using entries().reduce gave an error for me, this version works
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce

2022-01-27 07:02 UTC, dvmoritzschoefl commented
> Hi @dvmoritzschoefl, thanks for making the changes! Looks like we're pretty close. I left a handful of comments, just to make the code a bit more functional rather than imperative. Two other high-level comments:
> 
> * `packages/vega/test/specs-valid.json` is currently deleted but shouldn't be.
> * `docs/*.js` will be built as part of the final version release, so you don't need to include them in this PR.

Yes sry I made a mistake checking these files in, should be ok by now. I changed your suggestions accordingly and made sure the lasso still works.

2022-01-27 14:23 UTC, arvind approved these changes
Thanks @dvmoritzschoefl! The updates look good to me, and apologies for the malformed suggestions — the dangers of writing JavaScript code on-the-fly in the GitHub editor textbox 🤦 

I've cc'ed @jheer to take a final look in case he notices anything I missed, and then we can merge 🙂

2022-01-27 15:14 UTC, dvmoritzschoefl commented
@arvind very nice, I will adjust the vega-lite PR to those changes tomorrow and ping you when I am finished

2022-03-08 02:06 UTC, jheer approved these changes

2022-03-08 02:06 UTC, merged