Add new example: table with a scrollbar
vega/vega pull request #3851
Opened 2023-12-26 21:54 UTC by avatorl

New Interaction Techniques example: a simple one-column table with a vertical scrollbar. The scrollbar responds to dragging the scrollbar with a mouse, mouse wheel scrolling, and the Page Up, Page Down, Arrow Up, and Arrow Down buttons.

2024-01-10 07:05 UTC, avatorl commented
@jheer  could you merge this or is there anything else I have to complete on my side?

2024-01-10 17:23 UTC, domoritz requested changes

2024-01-10 17:23 UTC, domoritz commented on docs/examples/warming-stripes.vg.json
> +      "url": "https://vega.github.io/vega/data/global-temp.csv",
this should not be needed if we properly load Vega datasets

2024-01-22 15:37 UTC, domoritz requested changes

2024-01-22 15:37 UTC, domoritz commented on docs/examples/img/column-line-dynamical.png
dynamic or dynamical?

2024-01-22 15:37 UTC, domoritz commented on docs/examples/column-line-dynamical.md
> +An example of a Vega visualization that automatically switches between a Column chart and a Line chart depending on the number of data points.
```suggestion
An example of a Vega visualization that automatically switches between a bar chart and a line chart depending on the number of data points.
```

2024-01-22 15:37 UTC, domoritz commented on docs/examples/column-line-dynamical.md
> +Use the slider to change the number of data points displayed on the chart. For more than 50 data points, the chart type will be changed from a Column chart to a Line chart (with interpolation).
```suggestion
Use the slider to change the number of data points displayed on the chart. For more than 50 data points, the chart type will be changed from a bar chart to a line chart (with interpolation).
```

2024-01-22 15:37 UTC, domoritz commented on docs/data/global-temp.csv
Let's not change it here since it should come from Vega datasets.

2024-01-22 15:37 UTC, domoritz commented on docs/data/table-matrix-flags.csv
Will it be a problem that we don't have this in Vega datasets? If we want it there, maybe we should support the whole world?

2024-01-22 15:37 UTC, domoritz commented on docs/data/table-matrix-trade.csv
Same as above. Is it a problem that we don't have this in Vega datasets? Maybe you can instead use an existing example dataset.

2024-05-17 00:12 UTC, avatorl commented on docs/examples/img/column-line-dynamical.png
renamed everywhere to "bar-line-toggle"

2024-05-17 00:19 UTC, avatorl commented on docs/data/global-temp.csv
The changes make the data up to date with the Vega datasets version... Just for consistency... Is there any issue with that?

2024-05-17 00:31 UTC, avatorl commented on docs/data/table-matrix-flags.csv
I removed this table visualization from this pull request for now.

2024-05-17 00:31 UTC, avatorl commented on docs/data/table-matrix-trade.csv
I removed this table visualization from this pull request for now.

2024-06-05 17:17 UTC, avatorl commented
@domoritz, could you merge this, or let me know if there is anything else I should resolve?

2024-06-07 15:14 UTC, domoritz approved these changes
Thank you. I just have two small comments and then we can merge. These are great!

2024-06-07 15:14 UTC, domoritz commented on docs/data/global-temp.csv
Datasets should be in https://github.com/vega/vega-datasets since otherwise they are not available in the Vega editor.

2024-06-07 15:14 UTC, domoritz commented on docs/examples/earthquakes-globe.vg.json
> +    "subtitle": "Click anywhere to pause/restart rotation",
```suggestion
    "subtitle": "Click anywhere to pause/resume rotation",

```

2024-06-07 16:15 UTC, avatorl commented on docs/data/global-temp.csv
Thanks. I got it. All new examples use either existing Vega datasets or dummy data generated inside of a specification. I've removed Example 5 that requires a new dataset from this PR (will get back to it in the future).

2024-06-10 02:31 UTC, domoritz commented on docs/_data/examples.json
> +        {"name": "warming-stripes"},
```suggestion
        {"name": "warming-stripes"},
```

2024-06-10 02:34 UTC, domoritz commented
Awesome. Thank you for the making these examples and sending them as a pull request.

2024-06-10 02:35 UTC, merged