fix(legend): add third mode, `discrete`, to `LegendType`
vega/vega pull request #3957
Opened 2024-08-02 15:40 UTC by hydrosquall

## Motivation

- Fix https://github.com/vega/vega/issues/3954

## Changes

- Adds a type to align with the runtime behavior, + docstring update

https://github.com/vega/vega/blob/ddd2bbff9897415be968fb60e2afa6c695c9eec4/packages/vega-parser/src/parsers/legend.js#L35-L36

(TODO: Check w/ @jheer to confirm if this is the intended behavior)

## Notes

- Broader question: would we be interested to have portions of the vega sub-packges converted to TS so that we don't have to sync `.d.ts` files with JS source code as a separate step?

2024-09-06 20:07 UTC, domoritz commented
> Broader question: would we be interested to have portions of the vega sub-packages converted to TS so we don't have to sync .d.ts files with JS source code as a separate step?

Yes, if we can figure out a way that doesn't degrade the developer experience. So for example if I change code in a linked Vega package, the Vega editor (in local dev mode) should update.

2024-09-06 20:09 UTC, domoritz requested changes
Please update the docs at https://vega.github.io/vega/docs/legends/ as well.

2024-09-08 17:42 UTC, hydrosquall commented
> Yes, if we can figure out a way that doesn't degrade the developer experience. So for example if I change code in a linked Vega package, the Vega editor (in local dev mode) should update.

Got it! I split this out to a separate issue. https://github.com/vega/vega/issues/3971

> Please update the docs

A separate followup would be to generate sections of the docs files (like this props table) from the JSDoc comments in the source code. For the time being, I made an manual update, thanks for the flagging this one.

2024-09-09 21:57 UTC, domoritz approved these changes

2024-09-10 13:26 UTC, merged